# Generated by Django 5.2.16 on 2026-08-04 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
